[package]
name = "programming-bitcoin-in-rust"
version = "0.1.0"
edition = "2021"
description = "Programming Bitcoin (implemented in Rust)"
publish = false

[dependencies]
hmac = "0.12.1"
ruint = "1.11.0"
sha2 = "0.10.8"
