#!/bin/bash

set -o pipefail
set -o nounset
set -o errexit

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && (pwd -W 2> /dev/null || pwd))
EXAMPLES_DIR=$(realpath "${SCRIPT_DIR}/../examples")

for example in ${EXAMPLES_DIR}/*.rs; do
  filename=$(basename ${example})
  target=${filename%.*}

  for exercise in ${EXAMPLES_DIR}/ch${target}/ex*.rs; do
    filename=$(basename ${exercise})
    number=$(cut -d '_' -f1 <<<"${filename}" | cut -c 3-)

    cargo run --example "${target}" "${number}"
  done

  if [[ -f "${EXAMPLES_DIR}/ch${target}/other/mod.rs" ]]; then
    cargo run --example "${target}" "0"
  fi
done
